### ISSUE TITLE
500 Internal Server Error in jupyter v1.0

### ISSUE THREAD

**Issue by zhuoqiang** [oschuett/appmode#39]
The app renders a page saying "500 : Internal Server Error" in jupyter v1.0

It seems that template parameter `get_frontend_exporters'` is missing

Here's the error log

```
[E 07:11:23.089 NotebookApp] Uncaught exception GET /apps/Untitled.ipynb?appmode_scroll=0 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/apps/Untitled.ipynb?appmode_scroll=0', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/site-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/site-packages/tornado/web.py", line 3174, in wrapper
        return method(self, *args, **kwargs)
      File "/site-packages/appmode/server_extension.py", line 86, in get
        self.write(self.render_template('appmode.html', **render_kwargs))
      File "/site-packages/notebook/base/handlers.py", line 519, in render_template
        return template.render(**ns)
      File "/site-packages/jinja2/asyncsupport.py", line 76, in render
        return original_render(self, *args, **kwargs)
      File "/site-packages/jinja2/environment.py", line 1008, in render
        return self.environment.handle_exception(exc_info, True)
      File "/site-packages/jinja2/environment.py", line 780, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/site-packages/jinja2/_compat.py", line 37, in reraise
        raise value.with_traceback(tb)
      File "/site-packages/appmode/appmode.html", line 1, in top-level template code
        {% extends "notebook.html" %}
      File "/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/site-packages/notebook/templates/page.html", line 154, in top-level template code
        {% block header %}
      File "/site-packages/notebook/templates/notebook.html", line 114, in block "header"
        {% for exporter in get_frontend_exporters() %}
    jinja2.exceptions.UndefinedError: 'get_frontend_exporters' is undefined
```

**Comment by oschuett** [comment]
Thanks a lot the fix!
