### ISSUE TITLE
ModuleNotFoundError: No module named 'appmode'

### ISSUE THREAD

**Issue by soichih** [oschuett/appmode#74]
When I run ` jupyter nbextension     enable --py --sys-prefix appmode` after pip installing appmode, I ran into this error message.

```
$ jupyter nbextension     enable --py --sys-prefix appmode
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.5) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/bin/jupyter-nbextension", line 11, in <module>
    load_entry_point('notebook==6.0.3', 'console_scripts', 'jupyter-nbextension')()
  File "/home/shayashi/.local/lib/python3.8/site-packages/jupyter_core/application.py", line 285, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/home/shayashi/.local/lib/python3.8/site-packages/traitlets/config/application.py", line 1043, in launch_instance
    app.start()
  File "/usr/lib/python3/dist-packages/notebook/nbextensions.py", line 983, in start
    super(NBExtensionApp, self).start()
  File "/home/shayashi/.local/lib/python3.8/site-packages/jupyter_core/application.py", line 274, in start
    self.subapp.start()
  File "/usr/lib/python3/dist-packages/notebook/nbextensions.py", line 891, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/usr/lib/python3/dist-packages/notebook/nbextensions.py", line 864, in toggle_nbextension_python
    return toggle(module,
  File "/usr/lib/python3/dist-packages/notebook/nbextensions.py", line 477, in enable_nbextension_python
    return _set_nbextension_state_python(True, module, user, sys_prefix,
  File "/usr/lib/python3/dist-packages/notebook/nbextensions.py", line 375, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/usr/lib/python3/dist-packages/notebook/nbextensions.py", line 1117, in _get_nbextension_metadata
    m = import_item(module)
  File "/home/shayashi/.local/lib/python3.8/site-packages/traitlets/utils/importstring.py", line 38, in import_item
    return __import__(parts[0])
ModuleNotFoundError: No module named 'appmode'
```

**Comment by soichih** [comment]
I am using pyenv where I have jupyter binary installed. When I do `jupyter nbextension enable`, I believe it should not be using anything under /usr/lib/python3/dist-packages, but the error message indicates that it is.. I wonder why.

**Comment by oschuett** [comment]
This looks more like an issue with pyenv or your local installation that with appmode itself.
